const colors = {
  light: {
    text: "#2C2C2C",
    tint: "#2D1B69",
    background: "#FAF5FF",
    foreground: "#2C2C2C",
    card: "#FFFFFF",
    cardForeground: "#2C2C2C",
    primary: "#2D1B69",
    primaryForeground: "#FFFFFF",
    secondary: "#F5F0FF",
    secondaryForeground: "#2D1B69",
    muted: "#F5F0FF",
    mutedForeground: "#8A7050",
    accent: "#6B4FA8",
    accentForeground: "#FFFFFF",
    destructive: "#ef4444",
    destructiveForeground: "#ffffff",
    border: "#DDD0F0",
    input: "#DDD0F0",
    deepIndigo: "#2D1B69",
    indigo2: "#3D2496",
    purpleMid: "#6B4FA8",
    lavenderMid: "#7B5EA7",
    lavender: "#9B7FD4",
    cream: "#F5F0FF",
    softWhite: "#FAF5FF",
    blush: "#DDD0F0",
    warmGold: "#C9A84C",
    gold: "#D4A843",
    mist: "#E8D5A3",
    charcoal: "#2C2C2C",
    sage: "#8A7050",
  },
  radius: 14,
};

export default colors;
