uploads = []
outputs = []

[[generated]]
id = "Q4klGy0j3VeZookjX23Ji"
uri = "file://artifacts/mobile/assets/images/icon.png"
type = "image"
title = "generated_image"

[[generated]]
id = "V5jgJCVtqkXIGbJmSwCD6"
uri = "file://artifacts/mobile/assets/images/ash-tree.png"
type = "image"
title = "ash tree botanical illustration"
