// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/gratitude/GratitudeList.tsx": () => import("../components/mockups/gratitude/GratitudeList.tsx"),
  "./components/mockups/mood/CheckIn.tsx": () => import("../components/mockups/mood/CheckIn.tsx"),
  "./components/mockups/mood/History.tsx": () => import("../components/mockups/mood/History.tsx"),
  "./components/mockups/affirmations/Mine.tsx": () => import("../components/mockups/affirmations/Mine.tsx"),
  "./components/mockups/affirmations/Today.tsx": () => import("../components/mockups/affirmations/Today.tsx"),
  "./components/mockups/vision-board/VisionBoard.tsx": () => import("../components/mockups/vision-board/VisionBoard.tsx")
};
